# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nikki's blog
email: nicolaus.moeller@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My personal blog.
baseurl: "/nicolaus1990.github.io/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  nicolaus1990

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
remote_theme: "nicolaus1990/jekyll-theme-minanimal"
#remote_theme: "nicolaus1990/minimal"
#remote_theme: "nicolaus1990/minima"
#remote_theme: "nicolaus1990/so-simple-theme"
#remote_theme: "mmistakes/jekyll-theme-basically-basic"
#remote_theme: mmistakes/minimal-mistakes
#remote_theme: "mmistakes/so-simple-theme"

#For jekyll-theme-mianimal
profilePic: /assets/img/nikkiBarbaraBild.png

#For miniaml theme
#logo: /assets/img/logo.png
#show_downloads: true
#google_analytics: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#Other options:
#source: DIR #Change the directory where Jekyll will read files
#destination: DIR #Site destination
#exclude: [DIR, FILE, ...] #Exclude directories and/or files from the conversion. These exclusions are relative to the site's source directory and cannot be outside the source directory. 
#include: [DIR, FILE, ...] #Force inclusion of directories and/or files in the conversion. .htaccess is a good example since dotfiles are excluded by default. 

